var foodList = [
    "American Chinese cuisine",
    "Biscuit",
    "Bread",
    "Cuisine of Antebellum America",
    "Baked potato",
    "Barbecue (see below for specific types)",
    "Bear claw",
    "Beef Manhattan",
    "Blue cheese dressing",
    "Blue-plate special",
    "Bookbinder soup",
    "Breakfast burrito",
    "Brunswick stew",
    "Buffalo burger",
    "Buffalo wing",
    "Bull roast",
    "Burnt ends",
    "Cajun cuisine",
    "Calf's liver and bacon",
    "Carne pizzaiola[citation needed]",
    "Carolina style",
    "Celery Victor",
    "Cheese dog",
    "Cheese fries",
    "Cheese steak",
    "Chicago-style_pizza",
    "Chicken à la King",
    "Chicken and waffles",
    "Chicken Divan",
    "Chicken fingers",
    "Chicken French",
    "Chicken fried bacon",
    "Chicken fried steak",
    "Chicken nugget",
    "Chicken parmigiana",
    "Chicken sandwich",
    "Chili con carne",
    "Chili dog",
    "Chimichanga",
    "Chips and dip",
    "Choco pie",
    "Chowder",
    "City chicken",
    "Clam cake",
    "Clam chowder",
    "Coleslaw",
    "Cordon bleu",
    "Corn chowder",
    "Corn dog",
    "Corn flakes",
    "Corn relish",
    "Corned beef",
    "Cornish game hen",
    "Cowboy beans",
    "Crab cake",
    "Creamed corn",
    "Creamed eggs on toast",
    "Deviled crab",
    "Deviled egg",
    "Domesticated turkey",
    "Doughnut",
    "Drunken chicken",
    "Eggo",
    "Eggs Benedict",
    "Eggs Neptune",
    "Energy bar",
    "Engastration",
    "Fajita",
    "Fortune cookie",
    "French dip",
    "Fried chicken",
    "Fried fish",
    "Fry sauce",
    "Frybread",
    "Garden salad",
    "German chocolate cake",
    "Goulash",
    "Greek-American cuisine",
    "Green bean casserole",
    "Grits",
    "Hamburger",
    "Hangtown fry",
    "Haystack",
    "Hog fry",
    "Home fries",
    "Hot chicken",
    "Hot chicken sandwich",
    "Ice cream cake",
    "Italian-American cuisine",
    "Italian beef",
    "Italian dressing",
    "Liver and onions",
    "Lobster Newberg",
    "Lobster roll",
    "London broil",
    "Lorna Doone",
    "Macaroni and cheese",
    "Macaroni salad",
    "Maple bacon donut",
    "Maraca pie",
    "Mashed potato",
    "Mashed pumpkin",
    "Meatcake",
    "Meatloaf",
    "Milk toast",
    "Milkshake",
    "Mission burrito",
    "Mozzarella sticks",
    "Muffuletta",
    "Mulligan stew",
    "Onion ring",
    "Oysters Rockefeller",
    "Pancakes",
    "Pasta salad",
    "Pastrami",
    "Patty",
    "Pemmican",
    "Pepperoni",
    "Pickled cucumber",
    "Pigs in blankets",
    "Pizza strips",
    "Ploye",
    "Popcorn",
    "Popover",
    "Poppyseed muffin",
    "Pork and beans",
    "Potato salad",
    "Potato skins",
    "Potato wedges",
    "Potatoes O'Brien",
    "Protein bar",
    "Pulled pork",
    "Pumpkin pie",
    "Rabbit pie",
    "Ranch dressing",
    "Reuben sandwich",
    "Ribs",
    "Rolled oyster",
    "Russian dressing",
    "Russian tea cake",
    "Salisbury steak",
    "Sandwich",
    "Sausage gravy",
    "Scampi",
    "Scrapple",
    "Seafood cocktail",
    "Senate bean soup",
    "Slinger",
    "Sloppy joe",
    "Smelt",
    "Sonofabitch stew",
    "Soul food",
    "Jambalaya",
    "Rice and gravy",
    "Shrimp Creole",
    "Spanish rice",
    "Gumbo",
    "Dirty Rice",
    "Andouille",
    "Bologna sausage",
    "Breakfast sausage",
    "Chaudin",
    "Chorizo",
    "Goetta",
    "Half-smoke",
    "Hot dog",
    "Italian hot dog",
    "Kielbasa",
    "Lebanon bologna",
    "Maxwell Street Polish",
    "Polish Boy",
    "Salami",
    "Vienna sausage",
]

module.exports = generateRandomFood(){
    console.log("hi");
}